### ISSUE TITLE
Add aPulse to the list of Open Source status pages

### ISSUE THREAD

**Issue by ybouane** [ivbeg/awesome-status-pages#147]
A small project I built because existing status page projects were not providing what I was looking for:
https://github.com/ybouane/aPulse

- Notifications (by telegram, discord, email, sms...)
- Highly configurable
- Easy to set up it's a single nodejs file called watcher.js that handles all of the monitoring.
- Minimalist dashboard with latency and error tracking

**Comment by ivbeg** [comment]
Added
