### ISSUE TITLE
Unsure why staytus is deprecated and darkpixel/statuspage is not

### ISSUE THREAD

**Issue by schierlm** [ivbeg/awesome-status-pages#76]
For darkpixel/statuspage:
- The provided docker image returns 404
- All recent contributions are dependabot upgrades, the last real contribution is from 2019.
- I was unable to get this running on a recent (Debian stable) machine, and googling the error codes suggested that it uses some Python/Django features that have since been deprecated and removed. And psycopg needs to be upgraded at least two minor versions to work with current Postgres databases, which results in other dependencies to fall over.

Also, the author states that he has migrated his own statuspage to staytus, so I would consider the project discontinuedd.

On the other hand, staytus looks quite maintained (yet it contains some small bugs from what I found).

Am I missing something? If you agree, I can send a pull request if desired.

**Comment by ivbeg** [comment]
Hi @schierlm ! I think it looks like discontinued. Feel free to send a pull request
